language: scala

# (from: http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# (from: http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  # NOTE: This is just working-test
  - sbt "runMain SimpleMain --times=2525 --fpath=./test"
  - sbt "runMain RestArgsMain --times=2525 --fpath=./test hogehoge foo piyo"

  - sbt "runMain SubcommandMain sub1 --times=23 --fpath=./dummy-file"
  - sbt "runMain SubcommandMain sub2 --name=Adam apple orange tomato"